name: task_master
description: "A new Flutter project."
version: 1.1.1+1
publish_to: "none"

environment:
  sdk: '>=3.10.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_bloc: ^9.1.1
  get_it: ^9.1.1
  flutter_secure_storage: ^9.2.4
  freezed: ^3.2.3
  dio: ^5.9.0
  shared_preferences: ^2.5.3
  freezed_annotation: ^3.1.0
  gap: ^3.0.1
  go_router: ^17.0.0
  retrofit: ^4.9.1
  json_annotation: ^4.9.0
  rxdart: ^0.28.0
  google_fonts: ^6.2.1
  intl: ^0.20.2
  calendar_pager:
    git: 
      url: https://github.com/PedroSchwarz/calendar_pager.git
  logging: ^1.3.0
  collection: ^1.19.1
  firebase_messaging: ^16.0.4
  firebase_core: ^4.2.1
  flutter_local_notifications: ^19.2.0
  socket_io_client: ^3.1.2
  fl_chart: ^1.0.0
  flutter_svg: ^2.1.0
  flutter_launcher_icons: ^0.14.3
  flutter_animate: ^4.5.2
  flutter_localizations: 
    sdk: flutter
  uuid: ^4.5.1
  visibility_detector: ^0.4.0+2
  firebase_crashlytics: ^5.0.5
  firebase_analytics: ^12.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.4.15
  retrofit_generator: ^10.2.0
  json_serializable: ^6.11.2

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/logo.svg
    - assets/icons/logo.png
  
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
